steps:

  - id: build-test-image
    dir: hello-cloudbuild
    name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      - -c
      - |
        docker image build --target build --tag greeting:test .

  - id: run-tests
    dir: hello-cloudbuild
    name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      - -c
      - |
        docker container run greeting:test go test

  - id: build-app
    dir: hello-cloudbuild
    name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      - -c
      - |
        docker image build --tag gcr.io/${PROJECT_ID}/greeting:${COMMIT_SHA} .


images:
  - gcr.io/${PROJECT_ID}/greeting:${COMMIT_SHA}
